### ISSUE TITLE
Spark job errors if record validity results in zero input records

### ISSUE THREAD

**Issue by ghukill** [WSULib/combine#140]
If the Record input validity limits an input Job to zero records, regardless of whether or not it's merged with another Job that may have records, it fails:

```
traceback: [
"Traceback (most recent call last): ",
" File "/tmp/spark-123a9042-d20e-4ceb-a9c6-161f079a9c42/userFiles-2bd02029-c61c-4be8-ae84-c9976ae677f0/jobs.py", line 725, in spark_function records_df=agg_df ",
" File "/tmp/spark-123a9042-d20e-4ceb-a9c6-161f079a9c42/userFiles-2bd02029-c61c-4be8-ae84-c9976ae677f0/jobs.py", line 930, in save_records bounds = get_job_db_bounds(job) ",
" File "/tmp/spark-123a9042-d20e-4ceb-a9c6-161f079a9c42/userFiles-2bd02029-c61c-4be8-ae84-c9976ae677f0/jobs.py", line 964, in get_job_db_bounds start_id = records.first().id ",
"AttributeError: 'NoneType' object has no attribute 'id' "
]
```

This error is almost uniformly when it has nothing to work with.

**Comment by ghukill** [comment]
Addressed.
