### ISSUE TITLE
Exceeding memory for OAI Harvests for large sets

### ISSUE THREAD

**Issue by ghukill** [WSULib/combine#26]
After some testing, it would appear that OAIHarvester is failing for harvests where a *single* OAI set exceeds a threshold of records.  Tested to work with sets ~46k, but consistent failure for sets ~90k, which suggests the number is somewhere in the middle.

Encountered this problem once before when ingesting VMC collection, which was 38k.  Bumped up memory for executors the following which fixed:
```
# memory
spark.driver.memory 2g
spark.executor.memory 2g
spark.driver.cores 1
spark.executor.instances 1
```

However, looking like we might be encountering this again?  

Receiving the following error in the executor logs:
```
java.lang.OutOfMemoryError: Java heap space
```

Could potentially bump the memory for the executors (though not possible on current 8gb VM), but that would just "kick the can" with regards to this issue.  Holding off for now until speaking with DPLA folks to see if known issue.

We have observed there might be a "sweet spot" that obfuscate this issue.  In a typical harvest, it's quite common to have *many* sets, but of smaller size.  Or, because 90k is not that large, even just slightly higher memory for the Spark executors might be enough to avoid this problem.  If not resolved entirely, might be something for documentation where if this error is encountered, the only option is more memory?

**Comment by ghukill** [comment]
Running in pyspark, with very recent ingestion3 build:
```
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at scala.collection.immutable.List.$colon$colon(List.scala:112)
	at scala.collection.mutable.Stack.push(Stack.scala:105)
	at scala.xml.parsing.FactoryAdapter.startElement(FactoryAdapter.scala:126)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at scala.xml.factory.XMLLoader$class.loadXML(XMLLoader.scala:41)
	at scala.xml.XML$.loadXML(XML.scala:60)
	at scala.xml.factory.XMLLoader$class.loadString(XMLLoader.scala:60)
	at scala.xml.XML$.loadString(XML.scala:60)
	at dpla.ingestion3.harvesters.oai.OaiResponseProcessor$$anonfun$loadXml$1.apply(OaiResponseProcessor.scala:210)
	at dpla.ingestion3.harvesters.oai.OaiResponseProcessor$$anonfun$loadXml$1.apply(OaiResponseProcessor.scala:210)
	at scala.util.Try$.apply(Try.scala:192)
	at dpla.ingestion3.harvesters.oai.OaiResponseProcessor$.loadXml(OaiResponseProcessor.scala:210)
	at dpla.ingestion3.harvesters.oai.OaiResponseProcessor$$anonfun$getXml$1.apply(OaiResponseProcessor.scala:196)
	at dpla.ingestion3.harvesters.oai.OaiResponseProcessor$$anonfun$getXml$1.apply(OaiResponseProcessor.scala:196)
	at scala.util.Try$.apply(Try.scala:192)
	at dpla.ingestion3.harvesters.oai.OaiResponseProcessor$.getXml(OaiResponseProcessor.scala:195)
	at dpla.ingestion3.harvesters.oai.OaiResponseBuilder.getSinglePageResponse(OaiResponseBuilder.scala:203)
	at dpla.ingestion3.harvesters.oai.OaiResponseBuilder.loop$1(OaiResponseBuilder.scala:164)
	at dpla.ingestion3.harvesters.oai.OaiResponseBuilder.getMultiPageResponse(OaiResponseBuilder.scala:177)
	at dpla.ingestion3.harvesters.oai.OaiResponseBuilder$$anonfun$6.apply(OaiResponseBuilder.scala:118)
	at dpla.ingestion3.harvesters.oai.OaiResponseBuilder$$anonfun$6.apply(OaiResponseBuilder.scala:116)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
```

**Comment by ghukill** [comment]
Running from DPLA OAIHarvester from pyspark shell, with `2g` for executor memory, would reach 146k like clockwork before failure.  However, bumping up `spark.executor.memory` to `3g` the count reached 152k, but instead of failing with the above, receiving this:

```
[Stage 1:============================================>              (3 + 1) / 4]17/10/18 13:34:13 WARN netty.NettyRpcEnv: Ignored message: HeartbeatResponse(false)
17/10/18 13:34:15 WARN netty.NettyRpcEndpointRef: Error sending message [message = Heartbeat(driver,[Lscala.Tuple2;@730b6e66,BlockManagerId(driver, 10.0.2.15, 36589))] in 1 attempts
org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [10 seconds]. This timeout is controlled by spark.executor.heartbeatInterval
	at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:48)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:63)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:59)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:83)
	at org.apache.spark.rpc.RpcEndpointRef.askWithRetry(RpcEndpointRef.scala:102)
	at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$reportHeartBeat(Executor.scala:518)
	at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$1.apply$mcV$sp(Executor.scala:547)
	at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$1.apply(Executor.scala:547)
	at org.apache.spark.executor.Executor$$anon$1$$anonfun$run$1.apply(Executor.scala:547)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1877)
	at org.apache.spark.executor.Executor$$anon$1.run(Executor.scala:547)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:190)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:81)
	... 14 more
```

Still assuming memory failure...

**Comment by ghukill** [comment]
Another update:

Setting the following gets to 220k before `GC overhead limit exceeded`:
```
# memory
spark.driver.memory 3g
spark.executor.memory 3g
spark.driver.cores 1
spark.executor.instances 1
```

Some back of the envelope calculations where `2g` for `spark.executor.memory` was failing at 146k, suggested ~ 72.5k per `1g` of executor memory.  Predictions for `3g` were right around 219k, which aligns with this failing at 220k.

Increasing the `spark.driver.memory` to 3g fixed the `spark.rpc.RpcTimeoutException` problem, but one assumes it would present itself again at higher numbers similar to the `spark.executor.memory` issue.

**Comment by ghukill** [comment]
Update: potentially known issue related to very large sets with OAIHarvester.  Holding on this for now.

**Comment by ghukill** [comment]
Upgraded Ingestion3 build, should be fixed.
